name: Test
on: { push: { branches: [ main ] }, pull_request: { branches: [ main ] } }

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v4.1.1 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v4.0.1, with: { node-version: ">=20" } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v2.4.0, with: { version: "^8.14.1", run_install: true } }
    - run: scripts/test.sh
